services:
  web:
    build: .
    environment:
      - APP_DEBUG=true
      - APP_KEY=base64:PhmDXkgWk++CcPUPaiTiOcupGuA6cC1Hc/CY5NozQBg=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_marines
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=laravel_marines
    volumes:
      - laravel_marines_db:/var/lib/mysql


volumes:
  laravel_marines_db:
