services:
  web:
    build: .
    environment:
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_marines
      - DB_USERNAME=root
      - DB_PASSWORD=
    env_file: ./.env
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:80"
    restart: always
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=laravel_marines
    volumes:
      - laravel_marines_db:/var/lib/mysql
    command: --performance_schema=off
    restart: always


volumes:
  laravel_marines_db:
